name: Release

defaults:
  run:
    shell: nix develop --command bash {0}

on:
  push:
    tags:
      - "vibe-v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: TornaxO7/rust-template@v2-ci-actions
      - name: Generate changelog
        run: git cliff --workdir vibe --config vibe/config.toml --latest --output CHANGELOG.md
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: CHANGELOG.md